spring:
  data:
    mongodb:
      database: springCamp
      port: 27017
      host: localhost

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - com.ua.library.changelogs
