drop table if exists books;
drop table if exists authors;
drop table if exists genres;

create table authors
(
    id int8 generated by default as identity
        (START WITH 4),
    surname varchar(255),
    primary key (id)
);

create table genres
(
    id int8 generated by default as identity
        (START WITH 3),
    type varchar(255),
    primary key (id)
);

create table books
(
    id int8 generated by default as identity
        (START WITH 4),
    tittle varchar(255),
    author_id int8,
    genre_id int8,
    primary key (id)
);