spring:
  datasource:
#     url: jdbc:h2:mem:springCamp
    url: jdbc:postgresql://localhost:5432/springCamp
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

#    show-sql: true